{% set name = "urbansim_templates" %}
{% set version = "0.1.3" %}
{% set sha256 = "e080dc4a2a87ef18a03e551aae9c678ab8951bf6b9b04ab8f1e1b657e909fed6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - choicemodels >=0.2
    - numpy >=1.14
    - orca >=1.4
    - pandas >=0.22
    - patsy >=0.4
    - statsmodels >=0.8

test:
  imports:
    - urbansim_templates

about:
  home: https://github.com/udst/urbansim_templates
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Building blocks for simulation models'
  description: UrbanSim Templates is a Python library that provides building blocks for Orca-based simulation models
  doc_url: https://urbansim-templates.readthedocs.io/
  dev_url: https://github.com/udst/urbansim_templates

extra:
  recipe-maintainers:
    - smmaurer
