travis:
  secure:
    BINSTAR_TOKEN: a/EGUtstOPaV4EMORaF6kRCKS+iMw7f2y+pO/p+h8xWxIGZBv+cfmi3KTWXl/7COqCNnQ7Wd9bV7Qg92bp0i3/yYlSoJfj517pmeMTdaWEkuzpRG6kreTyKiTThcmUkwUu5/zgOLr1efkX0us/Mgtw0sEjVTHK9McweFba+SfOS7pFHs3h6KHDTOs1QBsabQrbdOIgSmrLnavDepudd2lPwRH8UgcbW3/3PLP8Kcaxb08cEumsCrOCA5nj6G6j1Y5DRcSvBDgrsOOR47PUCYJs7EJBj1Iczr1KHe2nF0b4XCY2VQy4G8wmhVXEdeDS1izh8Ex2XfyiEVoUWMGcCPHFJcXs9EFnV8qqxhpeYv2ADwSIU6Brdr3jkWw82EzwjvTUnm5sAh4EKiTcMKnIOi9hx7ONnozwVSjFDdeMRG6bhyDKuShI3qmUNTMZDChLjnd4FQluc+7e3Wt+3udXgt1kqNHwhBH/g61HphhTxIdhr85/L5+sOuJQX8FP4UmxBNWdLKB0MRRNP/lpVQ8EHluS+f9MxdQ+gkIQCJ20Na48dYjbjmGP1WwsZviu+xIBaOZODDR1YHLeLYpjuqXxjusBdHDdhOU3Ydgo8HKVy7zAXgHEUhZ5vFt4W4E076gXFo2GQgtur+64lLFqXU0BnQNju89RqjxjGIEtEfxw4LfG4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
